#!/bin/bash
# List all integration tests with descriptions

echo "======================================"
echo "Integration Test Suite"
echo "======================================"
echo ""
echo "Full Stack Integration Tests (20 tests):"
echo ""
echo "  1. test_01_person_full_lifecycle"
echo "     → Create, read, update, delete Person with all services"
echo ""
echo "  2. test_02_all_entity_types_indexing"
echo "     → Verify ALL entity types (Person, Note, Location, Movie, Book, Container, Asset, Org) are indexed"
echo ""
echo "  3. test_03_hierarchical_tags"
echo "     → Test tag hierarchy creation, counting, and searching"
echo ""
echo "  4. test_04_relations_and_neo4j"
echo "     → Test entity relations, validation, and Neo4j sync"
echo ""
echo "  5. test_05_bulk_operations"
echo "     → Test count endpoint and bulk delete by filter"
echo ""
echo "  6. test_06_tag_filtering_all_types"
echo "     → Verify tag search works across all entity types"
echo ""
echo "  7. test_07_import_export_roundtrip"
echo "     → Test data export and import preserves all data"
echo ""
echo "  8. test_08_multi_user_isolation"
echo "     → Verify users can only access their own data"
echo ""
echo "  9. test_09_search_with_multiple_filters"
echo "     → Test complex searches with type, tag, display, and query filters"
echo ""
echo " 10. test_10_tag_persistence_on_zero_count"
echo "     → Verify tags persist when count reaches zero (Gmail-style)"
echo ""
echo " 11. test_11_meilisearch_sync_on_update"
echo "     → Test that MeiliSearch updates when entities are modified"
echo ""
echo " 12. test_12_special_characters_in_tags"
echo "     → Test tags with spaces, dashes, dots, parentheses"
echo ""
echo " 13. test_13_concurrent_tag_updates"
echo "     → Test that concurrent tag updates maintain correct counts"
echo ""
echo " 14. test_14_relation_type_validation"
echo "     → Test that relation type validation works correctly"
echo ""
echo " 15. test_15_empty_and_null_tags"
echo "     → Test handling of empty and null tags"
echo ""
echo " 16. test_16_hierarchical_tag_expansion"
echo "     → Test that parent tag searches return all child tag entities"
echo ""
echo " 17. test_17_entity_type_specific_fields"
echo "     → Test that type-specific fields are properly stored and searchable"
echo ""
echo " 18. test_18_tag_tree_api"
echo "     → Test the tag tree API returns correct hierarchical structure"
echo ""
echo " 19. test_19_bulk_delete_with_relations"
echo "     → Test that bulk delete properly cleans up relations"
echo ""
echo " 20. test_20_display_field_search_restriction"
echo "     → Test that display-only search doesn't search other fields"
echo ""
echo "======================================"
echo "Stress Tests (1 test):"
echo ""
echo " 21. test_large_batch_import"
echo "     → Test importing 100 entities with hierarchical tags"
echo ""
echo "======================================"
echo "Total: 21 tests"
echo "Expected runtime: 3-5 minutes"
echo "======================================"
echo ""
echo "Run all tests:"
echo "  ./run_integration_tests.sh"
echo ""
echo "Run single test:"
echo "  docker compose -f docker-compose.local.yml exec backend python manage.py test \\"
echo "    people.tests.test_integration_full_stack.FullStackIntegrationTest.test_01_person_full_lifecycle"
echo ""
