# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_slug', models.CharField(db_index=True, max_length=64)),
                ('relpath', models.CharField(max_length=1000)),
                ('parent', models.CharField(blank=True, db_index=True, default='', max_length=1000)),
                ('filename', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('artist', models.CharField(blank=True, default='', max_length=500)),
                ('album', models.CharField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mtime', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['folder_slug', 'relpath'],
            },
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['artist'], name='audiotrack_artist_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['album'], name='audiotrack_album_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiotrack',
            constraint=models.UniqueConstraint(fields=('folder_slug', 'relpath'), name='audiotrack_folder_relpath'),
        ),
    ]
