# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='composer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['genre'], name='audiotrack_genre_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['year'], name='audiotrack_year_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['composer'], name='audiotrack_composer_idx'),
        ),
    ]
