# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0002_track_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='has_cover',
            field=models.BooleanField(default=False),
        ),
    ]
