# Generated by Django 6.0.1 on 2026-01-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_dob_alter_person_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
