# Generated by Django 6.0.1 on 2026-01-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_entityrelation_relation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
