# Generated by Django 6.0.1 on 2026-01-29 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('source', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('gemini', 'Gemini'), ('claude', 'Claude'), ('other', 'Other')], default='other', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('turn_count', models.IntegerField(default=0)),
                ('source_conversation_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.IntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('model', 'Model'), ('system', 'System')], max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('embedding_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='people.conversation')),
            ],
            options={
                'ordering': ['turn_number'],
                'indexes': [models.Index(fields=['conversation', 'turn_number'], name='people_conv_convers_4c459a_idx'), models.Index(fields=['role'], name='people_conv_role_5cfd66_idx')],
                'unique_together': {('conversation', 'turn_number')},
            },
        ),
    ]
