# Generated by Django 6.0.1 on 2026-01-29 07:35

from django.db import migrations


def assign_default_user(apps, schema_editor):
    """Assign all existing entities to a default user"""
    Entity = apps.get_model('people', 'Entity')
    User = apps.get_model('auth', 'User')
    
    # Get or create a default user
    default_user, created = User.objects.get_or_create(
        username='default_user',
        defaults={
            'email': 'default@example.com',
            'is_staff': False,
            'is_superuser': False
        }
    )
    
    if created:
        print(f"Created default_user")
    
    # Assign all entities without a user to the default user
    count = Entity.objects.filter(user__isnull=True).update(user=default_user)
    print(f"Assigned {count} entities to default_user")


def reverse_assign(apps, schema_editor):
    """Reverse migration - set user to null"""
    Entity = apps.get_model('people', 'Entity')
    Entity.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_entity_user_entity_people_enti_user_id_b11e19_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_default_user, reverse_assign),
    ]
