# Generated by Django 5.2.10 on 2026-01-30 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_remove_conversation_models'),
    ]

    operations = [
        # Save existing relations, recreate table with UUID primary key
        migrations.RunSQL(
            # Forward: Recreate table with UUID primary key (PostgreSQL version)
            sql="""
                -- Create temporary table with old data
                CREATE TEMPORARY TABLE temp_entityrelation AS 
                SELECT from_entity_id, to_entity_id, relation_type, created_at 
                FROM people_entityrelation;
                
                -- Drop old table
                DROP TABLE people_entityrelation CASCADE;
                
                -- Create new table with UUID primary key (using UUID type for PostgreSQL)
                CREATE TABLE people_entityrelation (
                    id UUID NOT NULL PRIMARY KEY,
                    from_entity_id UUID NOT NULL,
                    to_entity_id UUID NOT NULL,
                    relation_type varchar(50) NOT NULL,
                    created_at timestamp NOT NULL,
                    FOREIGN KEY (from_entity_id) REFERENCES people_entity (id) ON DELETE CASCADE,
                    FOREIGN KEY (to_entity_id) REFERENCES people_entity (id) ON DELETE CASCADE,
                    UNIQUE (from_entity_id, to_entity_id, relation_type)
                );
                
                -- Copy data back with new UUIDs (PostgreSQL version)
                INSERT INTO people_entityrelation (id, from_entity_id, to_entity_id, relation_type, created_at)
                SELECT 
                    gen_random_uuid(),
                    from_entity_id::UUID,
                    to_entity_id::UUID,
                    relation_type,
                    created_at
                FROM temp_entityrelation;
                
                -- Create indexes
                CREATE INDEX people_entityrelation_from_entity_id_idx ON people_entityrelation (from_entity_id);
                CREATE INDEX people_entityrelation_to_entity_id_idx ON people_entityrelation (to_entity_id);
            """,
            # Reverse: Not easily reversible, but provide a basic structure
            reverse_sql="""
                CREATE TEMPORARY TABLE temp_entityrelation AS 
                SELECT from_entity_id, to_entity_id, relation_type, created_at 
                FROM people_entityrelation;
                
                DROP TABLE people_entityrelation CASCADE;
                
                CREATE TABLE people_entityrelation (
                    id SERIAL PRIMARY KEY,
                    from_entity_id UUID NOT NULL,
                    to_entity_id UUID NOT NULL,
                    relation_type varchar(50) NOT NULL,
                    created_at timestamp NOT NULL,
                    FOREIGN KEY (from_entity_id) REFERENCES people_entity (id) ON DELETE CASCADE,
                    FOREIGN KEY (to_entity_id) REFERENCES people_entity (id) ON DELETE CASCADE,
                    UNIQUE (from_entity_id, to_entity_id, relation_type)
                );
                
                INSERT INTO people_entityrelation (from_entity_id, to_entity_id, relation_type, created_at)
                SELECT from_entity_id, to_entity_id, relation_type, created_at
                FROM temp_entityrelation;
            """
        ),
    ]
