# Generated by Django 6.0.5 on 2026-06-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5 stars')),
                ('review_content', models.TextField(help_text='Detailed review (Markdown supported)')),
                ('summary', models.TextField(help_text='Brief summary/highlights of the book')),
                ('read_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(help_text='Composer, singer, or group', max_length=200)),
                ('genre', models.CharField(help_text='e.g. Classical, Ghazal, Folk', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Notes on the track/rag/composition')),
                ('youtube_url', models.URLField(blank=True, help_text='Link to YouTube or audio source', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unique slug for the page URL (e.g. professional-life)', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Markdown content of the page')),
                ('is_protected', models.BooleanField(default=False, help_text='If checked, users must be logged in to view this page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='e.g. Photography, Video AI Internships', max_length=100)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='in_progress', max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Optional project cover image link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField(help_text='List of ingredients (one per line or markdown format)')),
                ('instructions', models.TextField(help_text='Steps to prepare')),
                ('prep_time_minutes', models.PositiveIntegerField(default=15)),
                ('image_url', models.URLField(blank=True, help_text='Link to recipe photo', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('active', 'Active'), ('done', 'Done')], default='backlog', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which items appear in the submenu')),
                ('external_url', models.CharField(blank=True, help_text='Optional external link (e.g. github URL)', max_length=300, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item. Leave blank for root-level items.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
                ('page', models.ForeignKey(blank=True, help_text="The page this menu item links to. Leave blank if it's just a category folder.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.page')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
