# Generated by Django 6.0.5 on 2026-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='render_as_html',
            field=models.BooleanField(default=False, help_text='If checked, render page content as raw HTML instead of Markdown'),
        ),
    ]
