# Generated by Django 6.0.5 on 2026-06-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staticfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text="If unchecked, this item won't be rendered in the header dropdown menu but can still be navigated to via links and generate breadcrumbs"),
        ),
    ]
