# Generated by Django 6.0.5 on 2026-06-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menuitem_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='render_as_html',
            field=models.BooleanField(default=False, help_text='If checked, render description content as raw HTML instead of Markdown'),
        ),
        migrations.AddField(
            model_name='workflowidea',
            name='render_as_html',
            field=models.BooleanField(default=False, help_text='If checked, render description content as raw HTML instead of Markdown'),
        ),
    ]
