# Generated by Django 6.0.5 on 2026-06-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_render_as_html_workflowidea_render_as_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workflowidea',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
