# Generated by Django 6.0.5 on 2026-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Optional category to group pages', max_length=100),
        ),
    ]
