# Generated by Django 6.0.5 on 2026-06-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_page_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='full_path',
            field=models.CharField(blank=True, default='', help_text='Computed full hierarchical path of the menu item', max_length=500),
        ),
    ]
