# Generated by Django 6.0.5 on 2026-06-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_menuitem_full_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticfile',
            name='file_url',
            field=models.URLField(blank=True, help_text='Or paste/drop a URL here to upload from the internet', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staticfile',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDFs, images, or documents here', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='staticfile',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Descriptive title for the file', max_length=200),
        ),
    ]
