# Generated by Django 6.0.5 on 2026-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_staticfile_file_url_alter_staticfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticfile',
            name='filename',
            field=models.CharField(blank=True, default='', help_text='Optional custom filename (e.g. animation.gif). If blank, defaults to the uploaded file name.', max_length=200),
        ),
    ]
