# Generated by Django 6.0.5 on 2026-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_staticfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='idea', max_length=20),
        ),
    ]
