# Generated by Django 6.0.5 on 2026-06-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=0, help_text='Ranking order (ascending)'),
        ),
    ]
