# Generated by Django 6.0.5 on 2026-06-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=9000, help_text='Ranking order (ascending)'),
        ),
    ]
