# Generated by Django 6.0.5 on 2026-06-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_project_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(help_text='Slug of the page this data belongs to', max_length=100, unique=True)),
                ('data', models.JSONField(default=dict, help_text='JSON payload containing state data')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
