# Generated by Django 6.0.5 on 2026-06-08 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent project. Leave blank for root-level projects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='core.project'),
        ),
    ]
