# Generated by Django 6.0.5 on 2026-06-11 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_blogcategory_blogtag_blogpost_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preview_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
