# Generated by Django 6.0.5 on 2026-06-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_blogpost_preview_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticfile',
            name='make_local_copy',
            field=models.BooleanField(default=True, help_text='If checked and a URL is provided, download it and save a local copy.'),
        ),
    ]
