# Generated by Django 6.0.5 on 2026-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_staticfile_make_local_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.CharField(blank=True, help_text='Optional cover image URL or relative path (e.g. /api/media/uploads/filename.png)', max_length=500, null=True),
        ),
    ]
