# Generated by Django 6.0.5 on 2026-06-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(blank=True, default='google', help_text='Social auth provider (e.g. google, github)', max_length=50)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, user is unsubscribed from updates')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='allowed_emails',
            field=models.TextField(blank=True, default='', help_text='Optional comma-separated list of emails allowed to view this page (if protected)'),
        ),
    ]
