# Generated by Django 6.0.5 on 2026-06-13 18:50

from django.db import migrations, models

def migrate_is_protected_to_roles(apps, schema_editor):
    Page = apps.get_model('core', 'Page')
    for page in Page.objects.all():
        if getattr(page, 'is_protected', False):
            page.roles_with_access = 'user'
            page.save()

def reverse_migrate_is_protected_to_roles(apps, schema_editor):
    Page = apps.get_model('core', 'Page')
    for page in Page.objects.all():
        if page.roles_with_access:
            page.is_protected = True
            page.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_subscription_page_allowed_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='roles_with_access',
            field=models.CharField(blank=True, default='', help_text="Comma-separated roles allowed to view this page (e.g. 'user, superuser'). Leave blank for public access.", max_length=255),
        ),
        migrations.RunPython(migrate_is_protected_to_roles, reverse_migrate_is_protected_to_roles),
        migrations.RemoveField(
            model_name='page',
            name='is_protected',
        ),
    ]
