# Generated by Django 6.0.5 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_page_is_protected_page_roles_with_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='roles_with_access',
            field=models.CharField(blank=True, default='', help_text="Comma-separated roles allowed to view this menu item (e.g. 'user, superuser'). Leave blank for public access.", max_length=255),
        ),
    ]
