# Generated by Django 6.0.5 on 2026-08-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_siteevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='siteevent',
            new_name='core_siteev_created_008995_idx',
            old_name='core_siteev_created_6d3c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='siteevent',
            new_name='core_siteev_post_id_7c1b34_idx',
            old_name='core_siteev_post_id_8a2f0b_idx',
        ),
        migrations.RenameIndex(
            model_name='siteevent',
            new_name='core_siteev_page_id_c70aac_idx',
            old_name='core_siteev_page_id_1c4e9d_idx',
        ),
    ]
