# Generated by Django 5.2.17 on 2026-08-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gallery',
            new_name='gallery_gal_owner_i_d8aeed_idx',
            old_name='gallery_gal_owner_i_7c2e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='gallery',
            new_name='gallery_gal_access__49034d_idx',
            old_name='gallery_gal_access__b8c1d2_idx',
        ),
        migrations.RenameIndex(
            model_name='galleryitem',
            new_name='gallery_gal_gallery_0788fe_idx',
            old_name='gallery_gal_gallery_3a1b2c_idx',
        ),
    ]
