# Generated by Django 5.2.10 on 2026-03-07 20:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this account', max_length=255)),
                ('email_address', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('imap_host', models.CharField(help_text='IMAP server hostname (e.g., imap.gmail.com)', max_length=255)),
                ('imap_port', models.IntegerField(default=993, help_text='IMAP port (usually 993 for SSL)')),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('username', models.CharField(help_text='IMAP username (usually email address)', max_length=255)),
                ('password', models.CharField(help_text='IMAP password or app-specific password', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='ImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this import configuration', max_length=255)),
                ('mailbox', models.CharField(default='INBOX', help_text='Mailbox/folder to import from', max_length=255)),
                ('from_filter', models.CharField(blank=True, help_text='Filter by sender email', max_length=255)),
                ('to_filter', models.CharField(blank=True, help_text='Filter by recipient email', max_length=255)),
                ('subject_filter', models.CharField(blank=True, help_text='Filter by subject keywords', max_length=255)),
                ('labels', models.JSONField(blank=True, default=list, help_text='Gmail labels to filter by')),
                ('since_date', models.DateField(blank=True, help_text='Only import emails after this date', null=True)),
                ('max_emails', models.IntegerField(default=100, help_text='Maximum number of emails to import per run')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_configs', to='mail_archive.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Unique message ID from email header', max_length=500)),
                ('subject', models.TextField(blank=True)),
                ('from_address', models.CharField(max_length=500)),
                ('to_addresses', models.JSONField(default=list, help_text='List of recipient email addresses')),
                ('cc_addresses', models.JSONField(blank=True, default=list, help_text='List of CC email addresses')),
                ('bcc_addresses', models.JSONField(blank=True, default=list, help_text='List of BCC email addresses')),
                ('date', models.DateTimeField(help_text='Email sent date from headers')),
                ('received_date', models.DateTimeField(blank=True, help_text='Date received by server', null=True)),
                ('body_text', models.TextField(blank=True, help_text='Plain text body')),
                ('body_html', models.TextField(blank=True, help_text='HTML body')),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_count', models.IntegerField(default=0)),
                ('eml_file_path', models.CharField(help_text='Path to stored .eml file', max_length=1000)),
                ('file_size', models.IntegerField(default=0, help_text='Size of .eml file in bytes')),
                ('labels', models.JSONField(blank=True, default=list, help_text='Gmail labels')),
                ('thread_id', models.CharField(blank=True, help_text='Email thread ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When imported into system')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_archive.emailaccount')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='mail_archiv_user_id_e16dc3_idx'), models.Index(fields=['user', 'from_address'], name='mail_archiv_user_id_77e304_idx'), models.Index(fields=['user', 'subject'], name='mail_archiv_user_id_7d9b7b_idx')],
                'unique_together': {('user', 'message_id')},
            },
        ),
    ]
