# Generated by Django 5.2.12 on 2026-03-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importconfig',
            name='to_date',
            field=models.DateField(blank=True, help_text='Only import emails before this date', null=True),
        ),
    ]
