# Generated by Django 5.2.17 on 2026-08-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_assistant', '0002_summarizeschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailsummary',
            new_name='gmail_assis_user_id_8857d1_idx',
            old_name='gmail_assis_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='emailsummary',
            new_name='gmail_assis_gmail_i_a1c521_idx',
            old_name='gmail_assis_gmail_i_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='gmailaccount',
            new_name='gmail_assis_user_id_888b4c_idx',
            old_name='gmail_assis_user_id_0f3c8a_idx',
        ),
    ]
