# Generated by Django 6.0 on 2025-12-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCEL', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
