# Generated by Django 6.0 on 2025-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0004_task_output_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='mime_type',
            new_name='extension',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='size_bytes',
            new_name='size',
        ),
        migrations.AddField(
            model_name='file',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
