# Generated by Django 6.0 on 2025-12-18 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0005_rename_mime_type_file_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['hash'], name='hash_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('volume', 'path', 'name'), name='unique_file_location'),
        ),
    ]
