# Generated by Django 6.0 on 2025-12-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0006_file_last_seen_file_hash_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='exif',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
