# Generated by Django 6.0 on 2025-12-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0007_file_exif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='exif',
            new_name='meta',
        ),
    ]
