# Generated by Django 6.0 on 2025-12-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_catalog', '0009_alter_file_name_alter_file_path_alter_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mime',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
