# Generated by Django 6.0.5 on 2026-08-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vacation category',
                'verbose_name_plural': 'Vacation categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vacation tag',
                'verbose_name_plural': 'Vacation tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_group', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='vacation_list.vaccategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='vacation_list.vactag')),
            ],
            options={
                'verbose_name': 'Vacation item',
                'verbose_name_plural': 'Vacation items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('initial_tags', models.ManyToManyField(blank=True, related_name='lists', to='vacation_list.vactag')),
            ],
            options={
                'verbose_name': 'Vacation list',
                'verbose_name_plural': 'Vacation lists',
                'ordering': ['-modified_on'],
            },
        ),
        migrations.CreateModel(
            name='VacListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('need', models.BooleanField(default=True)),
                ('done', models.BooleanField(default=False)),
                ('in_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='vacation_list.vaclist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='vacation_list.vacitem')),
            ],
            options={
                'verbose_name': 'Vacation list item',
                'verbose_name_plural': 'Vacation list items',
                'ordering': ['item__name'],
                'constraints': [models.UniqueConstraint(fields=('item', 'in_list'), name='vacation_list_unique_item_per_list')],
            },
        ),
    ]
