# Generated by Django 5.2.14 on 2026-06-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='whatsappmedia',
            index=models.Index(fields=['wa_media_id'], name='wa_assistan_wa_medi_85f057_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['wa_from'], name='wa_assistan_wa_from_f9b1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['wa_timestamp'], name='wa_assistan_wa_time_00bd58_idx'),
        ),
    ]
