 python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --start-dir 1982 --volume PHOTO --db-path /home/ubuntu/TestData/index.db --skip-pattern "*.filerun*" --dry-run
 python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --start-dir 1982 --volume PHOTO --db-path /home/ubuntu/TestData/index.db --skip-pattern "*.filerun*" --skip-pattern "*.DS_Store" --dry-run
 python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --start-dir 1982 --volume PHOTO --db-path /home/ubuntu/TestData/index.db --skip-pattern "*.filerun*" --skip-pattern "*.DS_Store*" --dry-run
 python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --start-dir 1982 --volume PHOTO --db-path /home/ubuntu/TestData/index.db --skip-pattern "*.filerun*"  --dry-run
 2473  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --start-dir 1982 --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2
 2474  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --start-dir 1984 --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2
 2475  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1986
 2476  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1987
 2477  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1988
 2478  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1989
 2479  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1984 --start-dir 1986 --start-dir 1987
 2480  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1984 --start-dir 1986 --start-dir 1987 --start-dir 1988
 2481  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1984 --start-dir 1986 --start-dir 1987 --start-dir 1988 --start-dir 1989
 2482  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 1984 --start-dir 1986 --start-dir 1987 --start-dir 1988 --start-dir 1989 --verbose 2
 2483  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 1990 --start-dir 1992 --start-dir 1993 --start-dir 1994 --start-dir 1996 --verbose 2
 2484  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 1998 --start-dir 1999 --start-dir 2000 --verbose 2
 2485  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 2001 --start-dir 2002 --start-dir 2003 --verbose 2
 2486  python3 ~/monorepo/scripts/index_media.py --path /mnt/photo   --check-existing size --check-existing modified_date --volume PHOTO --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 2003 --start-dir 2004 --start-dir 2005 --verbose 2
