# Volume must be registered first, e.g.:
# python3 ~/monorepo/scripts/manage_volumes.py set photo --src-root /volume1/photo --mount /mnt/photo --db-path /home/ubuntu/data/media-index/files.db

python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --start-dir 1982 --db-path /home/ubuntu/TestData/index.db --skip-pattern "*.filerun*" --dry-run
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --start-dir 1982 --db-path /home/ubuntu/TestData/index.db --skip-pattern "*.filerun*" --skip-pattern "*.DS_Store" --dry-run
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --start-dir 1982 --db-path /home/ubuntu/TestData/index.db --skip-pattern "*.filerun*" --skip-pattern "*.DS_Store*" --dry-run
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --start-dir 1982 --db-path /home/ubuntu/TestData/index.db --skip-pattern "*.filerun*" --dry-run
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --start-dir 1982 --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --start-dir 1984 --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1986
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1987
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1988
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1989
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1984 --start-dir 1986 --start-dir 1987
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1984 --start-dir 1986 --start-dir 1987 --start-dir 1988
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/TestData/index.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --dry-run --verbose 2 --start-dir 1984 --start-dir 1986 --start-dir 1987 --start-dir 1988 --start-dir 1989
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 1984 --start-dir 1986 --start-dir 1987 --start-dir 1988 --start-dir 1989 --verbose 2
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 1990 --start-dir 1992 --start-dir 1993 --start-dir 1994 --start-dir 1996 --verbose 2
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 1998 --start-dir 1999 --start-dir 2000 --verbose 2
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 2001 --start-dir 2002 --start-dir 2003 --verbose 2
python3 ~/monorepo/scripts/index_media.py --volume photo --check-existing size --check-existing modified_date --db-path /home/ubuntu/data/media-index/files.db --literal-patterns --skip-pattern "/.filerun" --skip-pattern "/.DS_Store" --start-dir 2003 --start-dir 2004 --start-dir 2005 --verbose 2
