"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

# Load .env manually to avoid extra dependencies
ENV_FILE = BASE_DIR / '.env'
if ENV_FILE.exists():
    with open(ENV_FILE, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, val = line.split('=', 1)
                os.environ[key.strip()] = val.strip().strip("'").strip('"')

# ClickUp Integration
CLICKUP_API_TOKEN = os.environ.get('CLICKUP_API_TOKEN', '')

# Google OAuth (site login) — also used as fallback for Gmail mailbox OAuth
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

# Email processor (Gmail → classify → workflows)
EMAIL_WORKER_ENABLED = os.environ.get('EMAIL_WORKER_ENABLED', '1').lower() in ('1', 'true', 'yes')
EMAIL_GMAIL_CLIENT_ID = os.environ.get('EMAIL_GMAIL_CLIENT_ID', '')
EMAIL_GMAIL_CLIENT_SECRET = os.environ.get('EMAIL_GMAIL_CLIENT_SECRET', '')
EMAIL_OAUTH_REDIRECT_URI = os.environ.get('EMAIL_OAUTH_REDIRECT_URI', '')
EMAIL_PUBSUB_TOPIC = os.environ.get('EMAIL_PUBSUB_TOPIC', '')
EMAIL_PUBSUB_VERIFICATION_TOKEN = os.environ.get('EMAIL_PUBSUB_VERIFICATION_TOKEN', '')
EMAIL_OPENAI_API_KEY = os.environ.get('EMAIL_OPENAI_API_KEY', '') or os.environ.get('OPENAI_API_KEY', '')
EMAIL_OPENAI_MODEL = os.environ.get('EMAIL_OPENAI_MODEL', 'gpt-4.1-mini')
LOCALAI_URL = os.environ.get('LOCALAI_URL', '').rstrip('/')
LOCALAI_API_KEY = os.environ.get('LOCALAI_API_KEY', '')
LOCALAI_MODEL = (
    os.environ.get('LOCALAI_MODEL', '')
    or os.environ.get('GMAIL_LOCALAI_MODEL', '')
    or 'qwen3-32b'
)
# Optional YouTube transcript proxy (cloud IPs are often blocked).
YOUTUBE_WEBSHARE_USERNAME = os.environ.get('YOUTUBE_WEBSHARE_USERNAME', '')
YOUTUBE_WEBSHARE_PASSWORD = os.environ.get('YOUTUBE_WEBSHARE_PASSWORD', '')
YOUTUBE_HTTP_PROXY = os.environ.get('YOUTUBE_HTTP_PROXY', '')
# Apify transcript actor fallback (same token as bldrdojo gmail assistant).
APIFY_TOKEN = (
    os.environ.get('APIFY_TOKEN', '') or os.environ.get('APIFY_API_TOKEN', '')
).strip().strip("'").strip('"')
APIFY_YOUTUBE_TRANSCRIPT_ACTOR = (
    os.environ.get(
        'APIFY_YOUTUBE_TRANSCRIPT_ACTOR',
        'automation-lab/youtube-transcript',
    )
    or 'automation-lab/youtube-transcript'
).strip().strip("'").strip('"')
EMAIL_ALIAS_ROUTES = os.environ.get(
    'EMAIL_ALIAS_ROUTES',
    'writing_idea@kalra.com:writing_idea',
)
EMAIL_CLICKUP_LIST_ID = os.environ.get('EMAIL_CLICKUP_LIST_ID', '')
EMAIL_CLICKUP_SENDER_FIELD_ID = os.environ.get('EMAIL_CLICKUP_SENDER_FIELD_ID', '')
EMAIL_CONFIDENCE_AUTO = float(os.environ.get('EMAIL_CONFIDENCE_AUTO', '0.85'))
EMAIL_COMMAND_SESSION_TTL = int(os.environ.get('EMAIL_COMMAND_SESSION_TTL', '3600'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mpre*6e9qj+^6c355^03xiej@7(n7xx&4m&p571mxh$y10!36p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# YouTube embeds need a Referer. Django's default (same-origin) strips it and
# the player shows "Error 153: Video player configuration error".
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


# Application definition

INSTALLED_APPS = [
    'core',  # Placed first to allow overriding admin templates
    'vacation_list',
    'asset_manager',
    'audio_library.apps.AudioLibraryConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'devenkalra.com API',
    'DESCRIPTION': (
        'REST API for pages, menu, blog, and related content. '
        'Authenticate mutating requests with a Token header: '
        '`Authorization: Token <key>` (obtain via POST /api/auth/login/).'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'pages', 'description': 'CMS pages (CRUD by slug)'},
        {'name': 'menu', 'description': 'Navigation menu tree and menu items'},
        {'name': 'blog', 'description': 'Articles / blog posts, categories, tags, comments'},
        {'name': 'auth', 'description': 'Login, logout, CSRF, social auth'},
        {'name': 'content', 'description': 'Projects, ideas, books, tracks, recipes'},
        {'name': 'clickup', 'description': 'ClickUp integrations'},
        {'name': 'vacation-list', 'description': 'Packing lists (Vac* models)'},
        {'name': 'asset-manager', 'description': 'Physical asset inventory'},
        {'name': 'audio-library', 'description': 'NAS audio catalog and signed streams'},
    ],
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:311",
    "http://127.0.0.1:311",
    "https://devenkalra.com",
    "https://*.devenkalra.com",
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:311",
    "http://127.0.0.1:311",
    "https://devenkalra.com",
    "https://*.devenkalra.com",
]

# Ensure login cookies can be sent cross-origin in dev
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Media files (user uploads)
MEDIA_URL = '/api/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_URL = 'static/'

# Add this line to define the absolute deployment directory for assets
STATIC_ROOT = BASE_DIR / 'static'

# Frontend URL for shareable preview links
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:311')

# Increase max upload sizes to 50MB (default is 2.5MB) to prevent 413 Client Error
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

# Audio library: dedicated NAS user mount, one or more allowed folders.
# Format: slug=/abs/path,slug=/abs/path|Label   or a JSON list of {slug,path,label}
# Example: concerts=/mnt/audio/concerts,talks=/mnt/audio/talks|Talks
from audio_library.roots import parse_audio_library_roots
AUDIO_LIBRARY_ROOTS = parse_audio_library_roots(os.environ.get('AUDIO_LIBRARY_ROOTS', ''))
AUDIO_LIBRARY_EXTENSIONS = os.environ.get('AUDIO_LIBRARY_EXTENSIONS', '.mp3')
AUDIO_LIBRARY_SIGN_TTL = int(os.environ.get('AUDIO_LIBRARY_SIGN_TTL', '21600') or 21600)
