# Generated by Django 5.2.17 on 2026-09-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('production_type', models.CharField(choices=[('short_form_documentary', 'Short Form Documentary'), ('long_form_documentary', 'Long Form Documentary'), ('reel', 'Reel')], max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_on'],
            },
        ),
        migrations.CreateModel(
            name='ProductionAssetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In progress'), ('done', 'Done')], default='todo', max_length=24)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_statuses', to='productions.production')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('scene_type', models.CharField(blank=True, default='', max_length=128)),
                ('start_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('duration_seconds', models.DecimalField(decimal_places=3, default=10, max_digits=12)),
                ('visuals', models.TextField(blank=True, default='')),
                ('voiceover', models.TextField(blank=True, default='')),
                ('music', models.TextField(blank=True, default='')),
                ('fx_cues', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='productions.production')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_scenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SceneAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='productions.scene')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['user', 'is_archived'], name='prod_user_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionassetstatus',
            constraint=models.UniqueConstraint(fields=('production', 'name_key'), name='prod_asset_status_unique'),
        ),
        migrations.AddIndex(
            model_name='scene',
            index=models.Index(fields=['user', 'production'], name='prod_scene_user_prod_idx'),
        ),
    ]
