# Generated by Django - add tags to FoodSpot and Food

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodspot_food_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspot',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
