# Generated by Django 5.2.11 on 2026-02-20 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_uuid_primary_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodspot',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['added_by'], name='food_food_added_b_7f3f32_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['private'], name='food_food_private_c5f8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='foodspot',
            index=models.Index(fields=['added_by'], name='food_foodsp_added_b_745d25_idx'),
        ),
        migrations.AddIndex(
            model_name='foodspot',
            index=models.Index(fields=['private'], name='food_foodsp_private_03faea_idx'),
        ),
    ]
