# Generated by Django 5.2.11 on 2026-02-20 04:08
# Made idempotent for production where columns may already exist

from django.db import migrations


def add_private_columns(apps, schema_editor):
    """Add private columns if they don't exist (idempotent)."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE food_food
            ADD COLUMN IF NOT EXISTS private BOOLEAN NOT NULL DEFAULT FALSE
        """)
        cursor.execute("""
            ALTER TABLE food_foodspot
            ADD COLUMN IF NOT EXISTS private BOOLEAN NOT NULL DEFAULT FALSE
        """)


def add_indexes(apps, schema_editor):
    """Create indexes if they don't exist (idempotent)."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS food_food_added_b_7f3f32_idx
            ON food_food (added_by_id)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS food_food_private_c5f8fd_idx
            ON food_food (private)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS food_foodsp_added_b_745d25_idx
            ON food_foodspot (added_by_id)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS food_foodsp_private_03faea_idx
            ON food_foodspot (private)
        """)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_uuid_primary_keys'),
        migrations.swappable_dependency('auth.User'),
    ]

    operations = [
        migrations.RunPython(add_private_columns, noop),
        migrations.RunPython(add_indexes, noop),
    ]
