# Generated by Django 5.2.11 on 2026-02-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_add_food_spot_food_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodspotfoodrating',
            options={},
        ),
        migrations.RenameIndex(
            model_name='foodspotfoodrating',
            new_name='food_foodsp_food_sp_07aa7e_idx',
            old_name='food_foodsp_food_sp_3a8b2a_idx',
        ),
    ]
