# Generated by Django 5.2.11 on 2026-02-20 07:43
# Made idempotent: rename index only if old name exists

from django.db import migrations, connection


def noop(apps, schema_editor):
    pass


def rename_index_if_exists(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes
            WHERE indexname = 'food_foodsp_food_sp_3a8b2a_idx'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER INDEX food_foodsp_food_sp_3a8b2a_idx
                RENAME TO food_foodsp_food_sp_07aa7e_idx
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_add_food_spot_food_rating'),
    ]

    operations = [
        migrations.RunPython(rename_index_if_exists, noop),
    ]
