# Generated by Django 5.2.11 on 2026-02-21 04:52
# Made idempotent: private columns and indexes already added by 0011/0012

from django.db import migrations, connection


def noop(apps, schema_editor):
    pass


def ensure_state(apps, schema_editor):
    """Ensure private columns and indexes exist (idempotent)."""
    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE food_food ADD COLUMN IF NOT EXISTS private BOOLEAN NOT NULL DEFAULT FALSE")
        cursor.execute("ALTER TABLE food_foodspot ADD COLUMN IF NOT EXISTS private BOOLEAN NOT NULL DEFAULT FALSE")
        cursor.execute("CREATE INDEX IF NOT EXISTS food_food_added_b_7f3f32_idx ON food_food (added_by_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS food_food_private_c5f8fd_idx ON food_food (private)")
        cursor.execute("CREATE INDEX IF NOT EXISTS food_foodsp_added_b_745d25_idx ON food_foodspot (added_by_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS food_foodsp_private_03faea_idx ON food_foodspot (private)")


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_food_private_foodspot_private_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_state, noop),
    ]
