# Generated by Django 6.0.5 on 2026-08-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset category',
                'verbose_name_plural': 'Asset categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset tag',
                'verbose_name_plural': 'Asset tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('locator_code', models.CharField(blank=True, help_text='Physical locator code printed or encoded with the item.', max_length=255, null=True)),
                ('locator_type', models.CharField(blank=True, choices=[('LABEL', 'Label'), ('QR', 'QR Code'), ('EPC', 'EPC (RFID)')], default='', help_text='Type of locator: Label, QR, or EPC.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent_area', models.ForeignKey(blank=True, help_text='Parent area (e.g. Garage for a shelf in the garage).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='asset_manager.assetarea')),
                ('category', models.ForeignKey(blank=True, help_text='High-level category (e.g. Camera Gear, Documents).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_category_assets', to='asset_manager.assetcategory')),
                ('tags', models.ManyToManyField(blank=True, help_text="Free-form tags, e.g. 'Canon', 'Travel'.", related_name='%(app_label)s_%(class)s_tag_assets', to='asset_manager.assettag')),
            ],
            options={
                'verbose_name': 'Asset area',
                'verbose_name_plural': 'Asset areas',
            },
        ),
        migrations.CreateModel(
            name='AssetBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('locator_code', models.CharField(blank=True, help_text='Physical locator code printed or encoded with the item.', max_length=255, null=True)),
                ('locator_type', models.CharField(blank=True, choices=[('LABEL', 'Label'), ('QR', 'QR Code'), ('EPC', 'EPC (RFID)')], default='', help_text='Type of locator: Label, QR, or EPC.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='If this box is directly in an area.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='asset_manager.assetarea')),
                ('parent_box', models.ForeignKey(blank=True, help_text='If this box is inside another box.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_boxes', to='asset_manager.assetbox')),
                ('category', models.ForeignKey(blank=True, help_text='High-level category (e.g. Camera Gear, Documents).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_category_assets', to='asset_manager.assetcategory')),
                ('tags', models.ManyToManyField(blank=True, help_text="Free-form tags, e.g. 'Canon', 'Travel'.", related_name='%(app_label)s_%(class)s_tag_assets', to='asset_manager.assettag')),
            ],
            options={
                'verbose_name': 'Asset box',
                'verbose_name_plural': 'Asset boxes',
            },
        ),
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ass_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Asset photo',
                'verbose_name_plural': 'Asset photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('locator_code', models.CharField(blank=True, help_text='Physical locator code printed or encoded with the item.', max_length=255, null=True)),
                ('locator_type', models.CharField(blank=True, choices=[('LABEL', 'Label'), ('QR', 'QR Code'), ('EPC', 'EPC (RFID)')], default='', help_text='Type of locator: Label, QR, or EPC.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='Area containing this item (if not in a box).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='asset_manager.assetarea')),
                ('box', models.ForeignKey(blank=True, help_text='Box containing this item (if any).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='asset_manager.assetbox')),
                ('category', models.ForeignKey(blank=True, help_text='High-level category (e.g. Camera Gear, Documents).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_category_assets', to='asset_manager.assetcategory')),
                ('tags', models.ManyToManyField(blank=True, help_text="Free-form tags, e.g. 'Canon', 'Travel'.", related_name='%(app_label)s_%(class)s_tag_assets', to='asset_manager.assettag')),
            ],
            options={
                'verbose_name': 'Asset item',
                'verbose_name_plural': 'Asset items',
                'constraints': [models.CheckConstraint(condition=models.Q(('box__isnull', False), ('area__isnull', False), _negated=True), name='asset_manager_item_not_in_both_box_and_area')],
            },
        ),
        migrations.AddConstraint(
            model_name='assetbox',
            constraint=models.CheckConstraint(condition=models.Q(('parent_box__isnull', False), ('area__isnull', False), _negated=True), name='asset_manager_box_not_in_box_and_area'),
        ),
    ]
