# Generated by Django 5.2.10 on 2026-02-04 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('urls', models.JSONField(blank=True, default=list, null=True)),
                ('photos', models.JSONField(blank=True, default=list, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, null=True)),
                ('locations', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('value', models.FloatField(blank=True, null=True)),
                ('acquired_on', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
            ],
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('kind', models.CharField(blank=True, choices=[('School', 'School'), ('University', 'University'), ('Company', 'Company'), ('NonProfit', 'NonProfit'), ('Club', 'Club'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=50, null=True)),
            ],
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Unspecified', 'Unspecified'), ('Male', 'Male'), ('Female', 'Female'), ('Binary', 'Binary')], default='Unspecified', max_length=20, null=True)),
                ('emails', models.JSONField(default=list, null=True)),
                ('phones', models.JSONField(default=list, null=True)),
                ('profession', models.CharField(max_length=255, null=True)),
            ],
            bases=('people.entity',),
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('IS_CHILD_OF', 'Is Child Of'), ('IS_PARENT_OF', 'Is Parent Of'), ('IS_FRIEND_OF', 'Is Friend Of'), ('IS_COLLEAGUE_OF', 'Is Colleague Of'), ('IS_SPOUSE_OF', 'Is Spouse Of'), ('IS_MANAGER_OF', 'Is Manager Of'), ('WORKS_FOR_MGR', 'Works For Mgr'), ('IS_STUDENT_OF', 'Is Student Of'), ('IS_TEACHER_OF', 'Is Teacher Of'), ('HAS_STUDENT', 'Has Student'), ('IS_RELATED_TO', 'Is Related To'), ('LIVES_AT', 'Lives At'), ('HAS_RESIDENT', 'Has Resident'), ('IS_LOCATED_IN', 'Is Located In'), ('CONTAINS', 'Contains'), ('HAS_ACTOR', 'Has Actor'), ('ACTED_IN', 'Acted In'), ('HAS_DIRECTOR', 'Has Director'), ('DIRECTED', 'Directed'), ('HAS_MUS_DIRECTOR', 'Has Mus Director'), ('GAVE_MUSIC_TO', 'Gave Music To'), ('INSPIRED', 'Inspired'), ('IS_BASED_ON', 'Is Based On'), ('HAS_AS_AUTHOR', 'Has As Author'), ('IS_AUTHOR_OF', 'Is Author Of'), ('IS_LOCATION_OF', 'Is Location Of'), ('IS_CONTAINED_IN', 'Is Contained In'), ('IS_LOCATED_AT', 'Is Located At'), ('HAS', 'Has'), ('HAS_EMPLOYEE', 'Has Employee'), ('WORKS_AT', 'Works At'), ('HAS_MEMBER', 'Has Member'), ('IS_MEMBER_OF', 'Is Member Of'), ('STUDIES_AT', 'Studies At')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='people.entity')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='people.entity')),
            ],
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['user', 'type'], name='people_enti_user_id_b11e19_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['user', 'created_at'], name='people_enti_user_id_730f6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entityrelation',
            unique_together={('from_entity', 'to_entity', 'relation_type')},
        ),
    ]
