# Generated by Django 6.0.1 on 2026-01-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_emails_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='emails',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Male', 'Male'), ('Female', 'Female'), ('Binary', 'Binary')], default='Unspecified', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phones',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
