# Generated by Django 5.2.11 on 2026-02-21 04:07
# Made idempotent for production where table may already exist

from django.db import migrations


def create_userprofile_if_not_exists(apps, schema_editor):
    """Create people_userprofile table if it doesn't exist (idempotent)."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS people_userprofile (
                id BIGSERIAL PRIMARY KEY,
                displayname VARCHAR(255) NULL,
                user_id INTEGER NOT NULL UNIQUE REFERENCES auth_user(id) ON DELETE CASCADE
            )
        """)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_userprofile_displayname'),
    ]

    operations = [
        migrations.RunPython(create_userprofile_if_not_exists, noop),
    ]
