# Generated by Django 5.2.11 on 2026-02-21 04:51
# Made idempotent: table already created by 0003/0004

from django.db import migrations, connection


def noop(apps, schema_editor):
    pass


def ensure_userprofile_table(apps, schema_editor):
    """Create people_userprofile table if it doesn't exist (idempotent)."""
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS people_userprofile (
                id BIGSERIAL PRIMARY KEY,
                displayname VARCHAR(255) NULL,
                user_id INTEGER NOT NULL UNIQUE REFERENCES auth_user(id) ON DELETE CASCADE
            )
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_userprofile'),
    ]

    operations = [
        migrations.RunPython(ensure_userprofile_table, noop),
    ]
