# Generated by Django 6.0.1 on 2026-01-19 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_entity_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.entity')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('people.entity',),
        ),
    ]
