# Generated by Django 6.0.1 on 2026-01-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityrelation',
            name='relation_type',
            field=models.CharField(choices=[('IS_CHILD_OF', 'Is Child Of'), ('IS_PARENT_OF', 'Is Parent Of'), ('IS_FRIEND_OF', 'Is Friend Of'), ('IS_COLLEAGUE_OF', 'Is Colleague Of'), ('IS_SPOUSE_OF', 'Is Spouse Of'), ('IS_MANAGER_OF', 'Is Manager Of'), ('WORKS_FOR_MGR', 'Works For Mgr'), ('IS_STUDENT_OF', 'Is Student Of'), ('IS_TEACHER_OF', 'Is Teacher Of'), ('IS_RELATED_TO', 'Is Related To'), ('RELATED_TO_NOTE', 'Related To Note')], max_length=50),
        ),
    ]
