# Generated by Django 5.2.14 on 2026-06-01 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='encrypted_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('displayname', models.CharField(blank=True, max_length=255, null=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
            database_operations=[],
        ),
    ]
