# Generated by Django 5.2.14 on 2026-06-02 00:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_entity_encrypted_data_entity_is_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_references', to='people.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['file_path'], name='people_file_file_pa_9140d6_idx'), models.Index(fields=['entity', 'file_path'], name='people_file_entity__2b441a_idx')],
                'unique_together': {('entity', 'file_path')},
            },
        ),
    ]
