# Generated by Django 6.0.1 on 2026-01-29 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_conversation_conversationturn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['user', 'type'], name='people_enti_user_id_b11e19_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['user', 'created_at'], name='people_enti_user_id_730f6a_idx'),
        ),
    ]
